[build]
builder = "DOCKERFILE"
dockerfilePath = "./apps/api/Dockerfile"

[deploy]
startCommand = "node dist/index.js"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
