[build]
builder = "DOCKERFILE"
dockerfilePath = "./apps/api/Dockerfile"

[deploy]
startCommand = "pnpm run start:production"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10