[build]
builder = "docker"

[deploy]
startCommand = "docker-compose up -d"
healthcheckPath = "/health"
healthcheckTimeout = 100

[[services]]
name = "api"
dockerfile = "apps/api/Dockerfile"
[services.vars]
PORT = "3000"

[[services]]
name = "worker"
dockerfile = "apps/worker/Dockerfile"

[[services]]
name = "redis"
image = "redis:6-alpine"