[build]
builder = "nixpacks"
buildCommand = "cd apps/api && npm install && npm run build"

[deploy]
startCommand = "cd apps/api && npm run start:production"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10