app = 'firecrawl-scraper-js-winter-river-2387'
primary_region = 'iad'
kill_signal = 'SIGINT'
kill_timeout = '30s'

[build]

[processes]
  app = "pnpm run start:prod"
  # Comment out the worker process for now
  # worker = 'node --max-old-space-size=8192 dist/src/services/queue-worker.js'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 2
  processes = ['app']

  [http_service.concurrency]
    type = 'requests'
    hard_limit = 200
    soft_limit = 75

  [[http_service.checks]]
    interval = '30s'
    timeout = '15s'
    grace_period = '20s'
    method = 'GET'
    path = '/'

[[services]]
  protocol = 'tcp'
  internal_port = 8080
  processes = ['app']

  [[services.ports]]
    port = 80
    handlers = ['http']
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ['tls', 'http']

  [services.concurrency]
    type = 'connections'
    hard_limit = 30
    soft_limit = 12

[[vm]]
  size = 'performance-4x'
  processes = ['app']